<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="TraceabilityMetamodel" nsURI="http://TraceabilityMetamodel"
      nsPrefix="TraceabilityMetamodel">
    <eClassifiers xsi:type="ecore:EClass" name="TraceabilityModel">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="#/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="traceabilityLinks" upperBound="-1"
          eType="#/0/TraceabilityLink" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TraceabilityLink">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="#/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="#/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="#/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rightLinkEnd" upperBound="-1"
          eType="#/0/TraceabilityLinkEnd" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="leftLinkEnd" upperBound="-1"
          eType="#/0/TraceabilityLinkEnd" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="traceabilityContext"
          eType="#/0/TraceabilityContext" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TraceabilityLinkEnd">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="#/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="traceableArtefact" lowerBound="1"
          eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TraceabilityContext">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="#/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="#/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="traceabilityContextData"
          upperBound="-1" eType="#/0/TraceabilityContextData" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TraceabilityContextData">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="#/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#/1/String"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="PrimitiveTypes" nsURI="ASPm-PrimitiveTypes" nsPrefix="pt">
    <eClassifiers xsi:type="ecore:EDataType" name="Boolean" instanceClassName="boolean"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Double" instanceClassName="double"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Integer" instanceClassName="int"/>
    <eClassifiers xsi:type="ecore:EDataType" name="String" instanceClassName="java.lang.String"/>
  </ecore:EPackage>
</xmi:XMI>
